---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: fraud
  ports:
    - protocol: TCP
      port: 5000
      nodePort: 32032
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud-app
          image: ahmedcheibani/fraudapp:bb2a67a
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
